
server:
  port: 8090

spring:
  application:
    name: ms-gateway
  security:
    oauth2:
      client:
        provider:
          keycloak-test:
            issuer-uri: http://localhost:8080/realms/parcial-ximena-largo
        registration:
          keycloak-test:
            client-id: api-gateway-client
            client-secret: VEs9X31wxeuzJpFtAFSoTmOlMsFkyJoQ
            scope:
                -   openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8090/login/oauth2/code/keycloak
  cloud:
    gateway:
      default-filters: TokenRelay
      routes:
        - id: ms-bills
          uri: lb://ms-bills/
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=2
# Configuraciones de eureka
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
